{% set name = "python-installer" %}
{% set pypi_name = "installer" %}
{% set version = "0.5.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ pypi_name[0] }}/{{ pypi_name }}/{{ pypi_name }}-{{ version }}.tar.gz
  sha256: 0cd6bdab3b358cf7e8749370b99aef9e12202751271c5ddb22126599b34dc665

build:
  number: 0
  skip: true  # [py==30 or py==31 or py==32 or py==33 or py==34]
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
    - flit-core >=2,<3
  run:
    - configparser >=3.5  # [py<3]
    - importlib_resources  # [py<37]
    - python

test:
  imports:
    - installer
    - installer._compat

about:
  home: https://github.com/pradyunsg/installer
  summary: A library for installing Python wheels.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - hadim
