{% set name = "python-installer" %}
{% set pypi_name = "installer" %}
{% set version = "0.6.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ pypi_name[0] }}/{{ pypi_name }}/{{ pypi_name }}-{{ version }}.tar.gz
  sha256: f3bd36cd261b440a88a1190b1becca0578fee90b4b62decc796932fdd5ae8839

build:
  skip: True  # [py<38]
  number: 0
  script: {{ PYTHON }} -m pip install --no-deps . -vv

requirements:
  host:
    - pip
    - python
    - setuptools
    - wheel
    - flit-core 3.8.0
  run:
    - python

test:
  requires:
    - pip
  imports:
    - installer
  commands:
    - pip check

about:
  home: https://github.com/pypa/installer
  description: |
    This is a low-level library for installing a Python package from a wheel distribution.
    It provides basic functionality and abstractions for handling wheels and installing packages from wheels.
  summary: A library for installing Python wheels.
  license: MIT
  license_file: LICENSE
  license_family: MIT
  dev_url: https://installer.pypa.io/en/stable/
  doc_url: https://github.com/pypa/installer/tree/main/docs

extra:
  recipe-maintainers:
    - xhochy
